spring:
  application:
    name: gateway-service
  eureka :
    instance :
      leaseRenewalIntervalInSeconds : 1
zipkin :
  baseUrl: http://zipkin-server/

zuul:
  routes:
    client1:
      path: /body/*
      serviceId: bodyShape
    client2:
      path: /calories/*
      serviceId: CalculateBurnedCaloriesRate
    client3:
      path: /calculator/*
      serviceId: SumCalories
    client4:
      path: /body/**
      serviceId: bodyShape
    client5:
      path: /calculator/**
      serviceId: SumCalories
ribbon:
  eureka:
    enabled : true
  ConnectTimeout: 30000000
  ReadTimeout: 30000000
---
spring:
  profiles: zone1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
    registerWithEureka: true
    preferSameZoneEureka: false
  instance:
    metadateMap:
      zone: zone1
server:
  port: ${PORT:8765}


