spring:
  application:
    name: CalculateBurnedCaloriesRate
zipkin:
    baseUrl: http://zipkin-server/
---
spring:
  profiles: zone1
eureka:
  instance:
    metadataMap:
      zone: zone1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: ${PORT:9000}
---
spring:
  profiles: zone2
eureka:
  instance:
    metadataMap:
      zone: zone2
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
server:
  port: ${PORT:9001}

endpoints:
  shutdown:
    enabled: true
    sensitive: false

