spring:
  application:
    name: photoProcessing
zipkin:
    baseUrl: http://zipkin-server/
---
spring:
  profiles: zone1
eureka:
  instance:
    metadataMap:
      zone: zone1
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/

---
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/body-shape?userSSL=false
---
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
---
spring:
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8086
